# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  format:be:
    cmds:
      - go tool gofumpt -l -w .

  lint:be:
    cmds:
      - go tool golangci-lint run --fix ./...

  generate:be:
    aliases:
      - gen:be
    cmds:
      - go generate ./...

  format:fe:
    dir: frontend
    cmds:
      - pnpm run format

  lint:fe:
    dir: frontend
    cmds:
      - pnpm run lint

  generate:fe:
    dir: frontend
    aliases:
      - gen:fe
    cmds:
      - pnpm generate

  test:
    cmds:
      - go test ./...

  test:clean:
    cmds:
      - go clean -testcache
      - task: test

  build:
    cmds:
      - go build -v -o ./bin/ .

  build:docker:
    cmds:
      - docker build . -t arranhs/twitchets

  run:be:
    cmds:
      - go run .

  run:fe:
    dir: frontend
    cmds:
      - pnpm dev

  run:docker:
    deps: [build:docker]
    cmds:
      - |
        docker run --rm \
          --name twitchets \
          -p 5656:5656 \
          arranhs/twitchets
