# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  format:be:
    cmds:
      - go fmt ./...

  lint:be:
    cmds:
      - golangci-lint run

  format:fe:
    dir: frontend
    cmds:
      - pnpm run format

  lint:fe:
    dir: frontend
    cmds:
      - pnpm run lint

  test:
    cmds:
      - |
        go clean -testcache
        go test ./...

  build:
    cmds:
      - go build -v -o ./bin/ .

  build:docker:
    cmds:
      - docker build . -t arranhs/twitchets

  run:
    cmds:
      - go run .

  run:docker:
    deps: [build:docker]
    cmds:
      - |
        docker run --rm \
          --name twitchets \
          -p 5656:5656 \
          arranhs/twitchets
