# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  format:
    cmds:
      - go tool gofumpt -l -w .

  lint:
    cmds:
      - go tool golangci-lint run .

  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test ./...

  build:
    cmds:
      - go build -v -o ./bin/ .

  build:docker:
    cmds:
      - docker build . -t arranhs/twitchets

  run:
    cmds:
      - go run .

  run:docker:
    deps: [build:docker]
    cmds:
      - |
        docker run --rm \
          --name twitchets \
          -p 5656:5656 \
          arranhs/twitchets
