// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/ahobsonsayers/twitchets/config"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// PutConfigJSONRequestBody defines body for PutConfig for application/json ContentType.
type PutConfigJSONRequestBody = externalRef0.Config

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current configuration
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// Update configuration
	// (PUT /config)
	PutConfig(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get current configuration
// (GET /config)
func (_ Unimplemented) GetConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update configuration
// (PUT /config)
func (_ Unimplemented) PutConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutConfig operation middleware
func (siw *ServerInterfaceWrapper) PutConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config", wrapper.GetConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/config", wrapper.PutConfig)
	})

	return r
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse externalRef0.Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConfig500Response struct {
}

func (response GetConfig500Response) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PutConfigRequestObject struct {
	Body *PutConfigJSONRequestBody
}

type PutConfigResponseObject interface {
	VisitPutConfigResponse(w http.ResponseWriter) error
}

type PutConfig200Response struct {
}

func (response PutConfig200Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutConfig400Response struct {
}

func (response PutConfig400Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PutConfig500Response struct {
}

func (response PutConfig500Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get current configuration
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// Update configuration
	// (PUT /config)
	PutConfig(ctx context.Context, request PutConfigRequestObject) (PutConfigResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutConfig operation middleware
func (sh *strictHandler) PutConfig(w http.ResponseWriter, r *http.Request) {
	var request PutConfigRequestObject

	var body PutConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutConfig(ctx, request.(PutConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutConfigResponseObject); ok {
		if err := validResponse.VisitPutConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZ23LjuBH9lQ42D3aVbt6ZvQyf4ovGpYotO/a4XKmRKwWRLQo7IMDBxbYypa/Jn+TL",
	"UgBIiqIoj+T1Zp8kgQ10n+5Gdx/qG4lllkuBwmgSfSM6nmNG/ddMJsj1v06lmLHULeRK5qgMQ/+Y5uzv",
	"uHDfEtSxYrlhUpCI3Az/cTe6GZ5FcIsIN8Pjs8thL0tgJhUkaCjjGqSAuXwCI0FODWWCdIhZ5Egioo1i",
	"IiUd8txNZVfQzC0eX4+cKrcoVYKKREfLDomlFUZ5C/6qcEYi8kN/BaZfIOlXMIL0skNmnCrUkj+iUneK",
	"b0K4u7kAOYOPTu42yEGu5PMCNKpHVB7LdJFTrZlI4ZRLm/hD4eDKn0H54TZIbrGrv7C8KwvRbi6ZMA6V",
	"URZrIN8tOyTlckq9iZTzqxmJPu+E9txv+8TiL2gumDZMpEUclw/rvq1LFiI1E35adoiQhs1YTINzdlI/",
	"rm0p9XaI8Up88jCDmd7xsFYUlXepUnTRyJc6Gl2H8/Ny2SEKv1qmMCHR5zKJV8nUgFsFYGX9Q6VaTn/D",
	"2DhbGjm2kVDFA4hlgr2JOLVKoTB8AVLwBZyfANOgbZ5LZTDpTZxeFDZzFp6f1DRuphKJiHliqTS6d1pB",
	"WCUay9yZ/vJSMycRSZmZ22kvllmfzuVUS6HpApXuF6eQ5QrO9iTaALhVFBTmCrWLK8R+xSrvWtBonJgG",
	"M6cGaJ7zhSsIlHMIrgYeDtITYQVHrQGfc85i5h3nLiVLEhQwXQAFnWPswlbuXdPVm4hjsSg1gpCmlMcE",
	"nhjnYDWCmSMkOKOWmxCC9XqXMO2TZBP8JRMssxmUEnDARMxt4nTNEA9duXOHS8VSJiiHXLEYgWqgkKOK",
	"URia4kScBeUROGPbDhOyWj4MJs6kyqghEUmknXJcFR1hsymqxr24ZOKsRLF/OXq/7BB8RGFuWcY4Vcy0",
	"ZPrQCYDTB7oSg4yaeO4QHAx6A+jCUW/gAFSAB70PcEA5l0/a19aMCancKW5PwmYzVChi1If7gN4Dmmsn",
	"GX0O+XvtotMSZfrsoxyCl6MqU60ZbSYgl1YkGg7++5/DRlj97lfFbs28kYj5R8RXQG2r6OtA68XbNzwW",
	"o3ZX0+q1JOW8umWYVIIB2z71va7vk/PAluK+B8ifHUibfVo1nPYbGzzten1R3aFsDi6KRf1pRHBjT0Bc",
	"WOzsSV+Vg+98a0qZFC0Gn6NMFc3nLIZCxgVEI1Xx3N+YlS1rASqF2Wy96vUm4qPl3EOMYG5MrqN+/3vN",
	"oT/lctrPKBN9LkPAeqn84eKXD92LD4O9A3/jjXuDcP+4XG5vyucuvRbbplgjv2DLHTjOXacJV8CLwEzJ",
	"DMJZraNdZUqH2LaZ8p/SqmJ/OUXe3Vy8dNRRc1hx53YKi1+YQlqGr53u+HrPbOmAaUC/W3DX3O6uo9l5",
	"69jUNxrkmCqa7TotFuLlAcvdHOULT/StGru8uZ0Scs2KjWGs/by9p9zvVsGaHrM9nx0neZIq2Qz5dfHE",
	"lwtqzRyFcfp8rdOGuv76tvzFDQxG5izeNGY0A+u5U1l6nL97et6BjH5B0Fa5eYxpNxhbwb5adPVuIe1f",
	"Xnv5IKaiGvNyO+UsrnADNU1DXr6YHWI1qtCZN8hj8eT/5+d32wqFc/0LhaKov5sM3q8HsgITcS21ZlOO",
	"8Ei5RQ1UYTQRXTg/ubiK4EKKxFUL9/v2KoJbac28+Hlf/IR71KZYG5ZrQ1quXY4iuGQJpyLRYWV4HPnn",
	"cCxSzmhYHF9FMJaqPH08LH7WThrfl2s1jacR3MbSuOPDyv1xBPeUY6FsPCo2oRIwUhgE1yjYxRXpEIcv",
	"fNyHj6H/uBz5j+Gx/xgHkXF4Ni4kT/3HfSEy2pXRFQF6M0J3sxov3qBPr85t1NyNohTPqRklW3qiewij",
	"M5AKUiVtXi60z1S1m76ldZ+jCc36byfSfKQurI6AlTbu1XGDik4J4IW7tBNL3osfu/LRZLUrRny6Jluw",
	"YdQQXlc0W/knCU6JAdoq4GorM7pkvx1XJ/0Vn5AJgQPMcrOA4K7DYJf/XhQEJ/j5oRTzuRGknLU1me6R",
	"XxU2Q8Xi6sHvIdo7EuurpnuKNwE9qBxjZIkeDmiNfh96Z0D36C34do2CeSL9En3+XgN6Wya+1UM7o65d",
	"zD+MSb8ijl7H7wviVuJdJ5sNRr3Xy9r1uXH50NmLkO/rlHbaXriICqhdY/j8EDy2+0SSucaSu3ycUa6r",
	"tX+jkhtzyy/fYenj3dj5K7IiBLqRFtu7zft1ar5XcMueuxnWXTn9q0JcnPhnhHVjHA21brN5OjkmZtLz",
	"cGa4f3X/xEw8d7Fe73DH127MekSlg/OOeoPewPVfmaOgOSMRedcb9N67bkLN3MepH1d9OEXTNucaxfAx",
	"UII4vJOHlQFrLZJ4TeG7G2XcmFH9XaJQ51Lo0L5+HAz8zCOFKUo8Xb1M6P+mQ4EIWbLzf1cFl102c+jW",
	"xjFqPbMu4sEI55Sfgg0NzuViKnz2+NcPqJRUfjzUNsuoWhTDU+mJdfzLDsltixPv8oSa4MJdXXdt6677",
	"alGbE5ks/kivrdLRJeuyPWTN/2zq+Wc9zAR05XDuJ+D37Z5+pJwlmx58dVwKLzcO9DJ+k/blaP3cCxlT",
	"Dgk+Ipd55iIaZElBkomjvFHfv8rjc6lN9Ovg1wFZPiz/FwAA//9ncC/+FR4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
