// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/ahobsonsayers/twitchets/config"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// PutConfigJSONRequestBody defines body for PutConfig for application/json ContentType.
type PutConfigJSONRequestBody = externalRef0.Config

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current configuration
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// Update configuration
	// (PUT /config)
	PutConfig(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get current configuration
// (GET /config)
func (_ Unimplemented) GetConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update configuration
// (PUT /config)
func (_ Unimplemented) PutConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutConfig operation middleware
func (siw *ServerInterfaceWrapper) PutConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config", wrapper.GetConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/config", wrapper.PutConfig)
	})

	return r
}

type GetConfigRequestObject struct {
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse externalRef0.Config

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConfig500Response struct {
}

func (response GetConfig500Response) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PutConfigRequestObject struct {
	Body *PutConfigJSONRequestBody
}

type PutConfigResponseObject interface {
	VisitPutConfigResponse(w http.ResponseWriter) error
}

type PutConfig200Response struct {
}

func (response PutConfig200Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutConfig400Response struct {
}

func (response PutConfig400Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PutConfig500Response struct {
}

func (response PutConfig500Response) VisitPutConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get current configuration
	// (GET /config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// Update configuration
	// (PUT /config)
	PutConfig(ctx context.Context, request PutConfigRequestObject) (PutConfigResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request) {
	var request GetConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutConfig operation middleware
func (sh *strictHandler) PutConfig(w http.ResponseWriter, r *http.Request) {
	var request PutConfigRequestObject

	var body PutConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutConfig(ctx, request.(PutConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutConfigResponseObject); ok {
		if err := validResponse.VisitPutConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZ627bOvJ/lfnz/D8kgG9Jey4VUGDTNA2MTZxs0iJYNMGClsYWTylSJamk3sJPs2+y",
	"T7YYUrJlW3blnJzdT7KpIec+8+PoO4t1lmuFylkWfWc2TjHj/memE5T2H6daTcSUFnKjczROoH/Nc/FX",
	"nNGvBG1sRO6EVixiN2d/+zS8OXsfwS0i3JydvL8862UJTLSBBB0X0oJWkOoncBr02HGhWIe5WY4sYtYZ",
	"oaasw751p7qreEaLJ9dDYkWL2iRoWHQ077BYF8oZL8H/G5ywiP3UXyrTLzXpL9QI1PMOm0hu0Gr5iMZ8",
	"MnJThU83F6An8IHobgMd5EZ/m4FF84jG6zKe5dxaoaZwKnWR+EPh4MqfweXhNpVosWu/iLyrS9JuroVy",
	"pJUzBdaUfDXvsKnUY+5F5FJeTVj0uZW2537bRxF/QXchrBNqWvpx/rBq2zplSVIT4ed5hyntxETEPBin",
	"FftRbUvFt8OcZ+KDRzjMbMvDGrVYWJcbw2dr8VLXxtbV+WU+7zCDXwthMGHR5yqIl8G0pu7CAUvpHxas",
	"9fh3jB3JshZjGwFVvoBYJ9i7V6eFMaicnIFWcgbn70BYsEWea+Mw6d0TX1RFRhKev6tx3AwlFjH3JKba",
	"2d7pQoVloImMzvTJy13KIjYVLi3GvVhnfZ7qsdXK8hka2y9PYfOlOtuDaEPBraRgMDdoya8Q+5XCeNOC",
	"RUdkFlzKHfA8lzMqCFxKCKYGGQ6y96pQEq0F/JZLEQtvOEpKkSSoYDwDDjbHmNxW7V3h1btXJ2pWcQSl",
	"XUWPCTwJKaGwCC5FSHDCC+mCC1brXSKsD5JN5S+FElmRQUUBB0LFskiI1wTxkModHa6NmArFJeRGxAjc",
	"AoccTYzK8Sneq/eBeQQkbNNhSi+WD4OIE20y7ljEEl2MJS6LjiqyMZq1vLgU6n2lxf7l6PW8w/ARlbsV",
	"mZDcCNcQ6WdEAMQP7IIMMu7ilDQ4GPQG0IWj3oAUWCg86L2BAy6lfrK+tmZCaUOn0J5ETCZoUMVoD/dR",
	"eg/VqJ1k/FuI32vyToOX+Tfv5eC8HE0VauveFgpyXajEwsG//3W45la/+1m+WxFvqGL5AfEZqjZV9FVF",
	"68XbNzwRo6XULOxKkEq5yDJMFoRBt33qe53fR7LAluK+h5K/kJJF9nHZcJozNliaen1Z3aFqDuTFsv6s",
	"eXBjT9C4lJjkmT4rBl/51jQVWjUIfI56anieihhKGnKIRW7i1GfMUpYVB1XEYrJa9Xr36kMhpVcxgtS5",
	"3Eb9/o+aQ38s9bifcaH6UgeH9ab6p4tf33Qv3gz2dvyNF+4F3H08n29vyucUXrNtKNbpL9iQAyc5dZqQ",
	"Ap4EJkZnEM5qhHYLUTqsaMKUf9eFKfdXKPLTzcWuo47WwQqd2ykl3oFCGsBXqxxf7ZkNHXAatG/n3BWz",
	"Uzq61ltHrr4xL2xK3b7l5uuSvAYUUeLU8Kwt3CzJqwPm7SztK1f0fYHbvL6dymY1KWoabQC75qP3Rsw/",
	"rKg1Pm57btD95kmbZDN8rss3vvTwwqWoHPHzddM6Tr36Ze9CBD6czkW8KcxwAoW/h1VljEzfs2kHMv4F",
	"wRaGsJ2wBLILJb4WSLVzpov/e24iQ8zVAjLmxViKeKE3cLcuyO4k77DCogldfuMiWr7579n51baiQ6bf",
	"UXTW0m4jlhJ8bERVlezREsEH0oAhfZNTCTi9y4jUOnMjdDMkXbLI0Fo+Raho4aB7TCyOOhXwh8FhD7rH",
	"b6V+Qus60D2inx0YvFWE1mQHjt6mYpo2N/waxLKEAHfJolYqMFHDgUWEypCQ6DiA4UcuRRJI7OEuM4Qc",
	"+WE/O7ke1ntaxbBNlG5pa/QKvuCs/YHH62EW5C657IizEjNsTp38erhgw7261taKsUQyXoEWuMHoXnXh",
	"/N3FVQQXWiXU4ej/7VUEt7pwafn3rvwLd2hduXZWrZ3xau1yGMGlSCRXiQ0rZyeRfw8naioFD4ujqwhG",
	"2lSnj87Kv7WTRnfVWo3jaQS3sXZ0fFi5O4ngjkssmY2G5SY0CoYGA+HK2ODiinUY6Rced+Fx5h+XQ/84",
	"O/GPUSAZhXejkvLUP+5KkmHbKUTpoBcbQtwsIfELYMvluWttfqNgxSl3w2RLwNNLGL4HbWBqdJFXCzvL",
	"wvH29DxHF3LnL++0+8DJraAVfFxihvYoscqkUoEdudRqsrPXTIfK1fokZjnFOV2hLSc4aCGM2Nbh50cN",
	"xMQBbySgui2crQp3h4qQT/F7ds/gALPczSCY6zDI5X+XBYEIPz9UZD42AhVJW6PpHvlVVWRoRLx48UeG",
	"Qy2HQVfr5imnVz1YGMbpRds64LWR0aE3BnSPXmJGVOtpfviza+TzoxbystOjrRZqrXUtMf+06c8z/Oh5",
	"/DEnbh0W1Qcka1OgvT4wrN5P5g+dvYZI+xqledRUmogrqKUxfH4IFmuPfDNqLDnF44RLu1j7Jxq9gY9/",
	"/cFkadRuovSMqAiOXguL7d3m9eo4aS/nVj13061t51DPcnF54v/CrRvXnlDrNpsn0Qk10X52JJz0n5ue",
	"hItT8vVqhzu5Jpj1iMYG4x31Br0B9V+do+K5YBF71Rv0XlM34S71furHiz48RdeEc50R+BiunnH4jgRL",
	"AVZaJPOcwm+CMgQzFp/4DNpcKxva1/Fg4DGPVq4s8Xx5Yej/bkOBCFHS+ntrOT6Zr8fQbRHHaO2kII8H",
	"IcgoPwcZ1u725FPlo8ePzNAYbTw8tEWWcTMrwVNliVX9/fSowYif8oS7YMK2prsu6qb7WqB173Qy+zOt",
	"tgxHCtZ5s8vWvzPW46/waiZgFwaXHgG/brZ0uGduWPDZfimtvHagp/GbrC9Hq+de6JhLSPARpc4z8mig",
	"ZeUwhqXO5VHfj59lqq2Lfhv8NmDzh/l/AgAA//8ws8Z3ySAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
