// Package config provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package config

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/ahobsonsayers/twigots"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/orsinium-labs/enum"
)

// Defines values for NotificationType.
var (
	notificationTypeBuilder = enum.NewBuilder[string, NotificationType]()

	NotificationTypeGotify   = notificationTypeBuilder.Add(NotificationType{"gotify"})
	NotificationTypeNtfy     = notificationTypeBuilder.Add(NotificationType{"ntfy"})
	NotificationTypePushover = notificationTypeBuilder.Add(NotificationType{"pushover"})
	NotificationTypeTelegram = notificationTypeBuilder.Add(NotificationType{"telegram"})

	NotificationTypes = notificationTypeBuilder.Enum()
)

// Config defines model for Config.
type Config struct {
	// APIKey REQUIRED: See README.md for details on how to obtain
	APIKey string `json:"apiKey"`

	// Country Country code.
	// Currently only GB is supported.
	Country Country `json:"country"`

	// FlaresolverrUrl URL of FlareSolverr proxy server for bypassing Cloudflare (Optional)
	FlaresolverrUrl string `json:"flaresolverrUrl,omitempty"`

	// Notification Notification service configuration
	Notification       NotificationConfig        `json:"notification"`
	GlobalTicketConfig GlobalTicketListingConfig `json:"global"`
	TicketConfigs      []TicketListingConfig     `json:"tickets"`
}

// Country Country code.
// Currently only GB is supported.
type Country = twigots.Country

// GlobalTicketListingConfig GlobalTicketListingConfig represents configuration settings that apply to all ticket listings
// unless explicitly overridden by a specific ticket configuration.
// Any setting not specified will use the default.
type GlobalTicketListingConfig struct {
	// EventSimilarity Event name similarity matching (0.0 - 1.0).
	// Default: 0.9 (allows for minor naming differences)
	EventSimilarity float64 `json:"eventSimilarity,omitempty"`

	// Regions Geographic regions to search for tickets.
	// Default: All regions if not specified.
	// Full list: https://github.com/ahobsonsayers/twigots/blob/main/location.go#L79-L90
	Regions []Region `json:"regions,omitempty"`

	// NumTickets Minimum number of tickets required in listing
	// Default: Any number of tickets.
	NumTickets int `json:"numTickets,omitempty"`

	// MinDiscount Minimum discount (including fee) on the original price as a percentage
	// Default: Any discount (including no discount).
	MinDiscount float64 `json:"discount,omitempty"`

	// MaxTicketPriceInclFee Maximum price per ticket (including fee) in pounds (£)
	// Default: Any price.
	MaxTicketPriceInclFee float64 `json:"maxTicketPrice,omitempty"`

	// Notification Notification services to use
	// Default: All configured services.
	Notification []NotificationType `json:"notification,omitempty"`
}

// GotifyConfig defines model for GotifyConfig.
type GotifyConfig struct {
	// Url Your Gotify server URL
	Url string `json:"url"`

	// Token Application token from Gotify
	Token string `json:"token"`
}

// NotificationConfig Notification service configuration
type NotificationConfig struct {
	Ntfy     *NtfyConfig     `json:"ntfy,omitempty"`
	Gotify   *GotifyConfig   `json:"gotify,omitempty"`
	Telegram *TelegramConfig `json:"telegram,omitempty"`
	Pushover *PushoverConfig `json:"pushover,omitempty"`
}

// NotificationType defines model for NotificationType.
type NotificationType enum.Member[string]

// Notifications defines model for Notifications.
type Notifications []NotificationType

// NtfyConfig defines model for NtfyConfig.
type NtfyConfig struct {
	// Url You can use the public instance at https://ntfy.sh
	Url string `json:"url"`

	// Topic If using https://ntfy.sh, make sure this is unique to you!
	Topic string `json:"topic"`

	// Username Username for authenticated instances (Optional)
	Username string `json:"username,omitempty"`

	// Password Password for authenticated instances (Optional)
	Password string `json:"password,omitempty"`
}

// PushoverConfig defines model for PushoverConfig.
type PushoverConfig struct {
	// Token Application API token from Pushover
	Token string `json:"token"`

	// User Your user key from Pushover
	User string `json:"user"`

	// Device Optional: specific device name to send to
	Device *string `json:"device,omitempty"`

	// Sound Optional: notification sound (see Pushover docs for valid sounds)
	Sound *string `json:"sound,omitempty"`

	// Priority Optional: message priority (-2 to 1, default 0). -2=lowest, -1=low, 0=normal, 1=high
	Priority *int `json:"priority,omitempty"`
}

// Region Region code.
// Possible values are:
// - GBLO: London
// - GBSO: South
// - GBSW: South West
// - GBSE: South East
// - GBMI: Midlands
// - GBEA: East Anglia
// - GBNO: North
// - GBNE: North East
// - GBNW: North West
// - GBSC: Scotland
// - GBWA: Wales
// - GBNI: Northern Ireland
type Region = twigots.Region

// Regions defines model for Regions.
type Regions []Region

// TelegramConfig defines model for TelegramConfig.
type TelegramConfig struct {
	// Token Get from @BotFather on Telegram
	Token string `json:"token"`

	// ChatId Your chat ID or group chat ID
	ChatId int `json:"chatId"`
}

// TicketListingConfig TicketListingConfig represents configuration for specific ticket listings
// Configuration overrides global configuration
// To reset a global configuration to its default, use:
// - "" (empty string) for string values
// - [] (empty array) for list values
// - -1 for numeric values
type TicketListingConfig struct {
	// Event Event name
	Event string `json:"event"`

	// EventSimilarity Event name similarity matching (0.0 - 1.0).
	// Overrides global setting.
	EventSimilarity *float64 `json:"eventSimilarity,omitempty"`

	// Regions Geographic regions to search for tickets
	// Overrides global setting. To reset to default (all regions), use an empty array [].
	Regions Regions `json:"regions,omitzero"`

	// NumTickets Number of tickets required in listing
	// Overrides global setting. To reset to default (any number), use -1.
	NumTickets *int `json:"numTickets,omitempty"`

	// MinDiscount Minimum discount on the original price as a percentage
	// Overrides global setting. To reset to default (any discount), use -1.
	MinDiscount *float64 `json:"discount,omitempty"`

	// MaxTicketPriceInclFee Maximum price per ticket (including fee) in pounds (£)
	// Overrides global setting. To reset to default (any price), use -1.
	MaxTicketPriceInclFee *float64 `json:"maxTicketPrice,omitempty"`

	// Notification Notification services to use
	// Overrides global setting. To reset to default (all configured services), use an empty array [].
	Notification Notifications `json:"notification,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8QZ7W7buvVVznj3IwFkJ2m7e1EBBZambmAscbKkRTDU/UFLxxJXitQlqSRe4afZm+zJ",
	"hkNKtmzLsZN2u78kHx2e7y8ef2eJLkqtUDnL4u/MJjkW3L+eaTUVGb2VRpdonEAP56X4G87oLUWbGFE6",
	"oRWL2c3g75+HN4MPMdwiws3g9MPloF+kMNUGUnRcSAtaQa4fwGnQE8eFYhFzsxJZzKwzQmUsYo+9TPcU",
	"Lwh4ej0kVgTUJkXD4pN5xBJdKWe8BH82OGUx++VoqcVRrcLRWY02j9hUcoNWy3s05rORm7J/vrkAPYWP",
	"hHcb8KA0+nEGFs09Gq/EZFZya4XK4EzqKvVE4eDK0+DycJsuBOzZb6Ls6Rq1V2qhHKnjTIUt7V7PI5ZJ",
	"PeFeRC7l1ZTFX55W89zjfxLJN3QXwjqhstpz86+r1mxj1igt3n+ZR0xpJ6Yi4cEqT/MdtXAbhhFznrqP",
	"E+GwsLuodMq9MCQ3hs/WYqItv20r8Ot8HjGDv1fCYMriL02gLgNmTcGFrZdif12w1pN/YuJIlrNluK0G",
	"Tf0BEp1if6zOKmNQOTkDreQMzt+DsGCrstTGYdofE0NUVUGinb9vsdoMFxYz9yAy7Wz/bCH7MphEQTR9",
	"ZnKXs5hlwuXVpJ/o4ojnemK1snyGxh7VVBiZZnugbGi2FRUMlgYtuRASD6mMNyZYdIRmweXcAS9LOaM0",
	"51JCMC7IQMiOVaUkWgv4WEqRCG8xyjiRpqhgMgMOtsSEHNWcXeHVH6tTNWs4gtKuwccUHoSUUFkElyOk",
	"OOWVdMH2q1UsFdaHxabyl0KJoiqgwYADoRJZpcRrinhIRYyIayMyobiE0ogEgVvgUKJJUDme4Vh9CMxj",
	"IGG7iCm9AB8GEafaFNyxmKW6mkhcVhRVFRM0a5lwKdSHRovn15o384jhPSp3KwohuRGuI8QHhADED+wC",
	"DQrukpw0ODjuH0MPTvrHpMBC4eP+WzjgUuoH6wtnIZQ2RIXOpGI6RYMqQXv4HKWfoRo1iYI/hvi9Ju90",
	"eJk/ei8H55VomlBb97ZQUOpKpRYO/vPvwzW3+tMv8t2KeEOVyI+IL1C1q2qvKtqu076biQQtpWZlV4JU",
	"ykWWYbpADLrtVcrbjD6R6lvq+DO0+5W0q4pPy6bSnarBxNTB60IOTR8g99WFZ811G2eCqrXEJE/2ouB7",
	"7btQJrTqEPgcdWZ4mYsEahzyhEVuktynylKWFc80yGK6Wu76Y/WxktKrGEPuXGnjo6Nd7eBoIvXkqOBC",
	"HUkdHNbP9C8Xv73tXbw93t/jN16qn+DnV/N5R+M9p4CabRtDnf6GHeF+WlJTCdHuUWBqdAGBVueItpAh",
	"YlXXbPgPXZn6fDMNfr65eIrUyfokQnSjWuKuEaNjltorj1f7YkeXy4LaO/y4YmhKObf7zMi1T5SVzamH",
	"7zp1XeO1Jj2UmBle7BwUa7zm5HyHGX0Fir8vJi6vU9QYpMW3JfzGSLZGc/+xdmctJMpue3DTReNBm3Qz",
	"DK7rL75a8MrlqBwx8qXOOk599edeSmhQcLoUyaYwwylU/kLUVB6yct/mERT8G4KtDM1hwtIkXCnxe4VU",
	"7ma6+tNLMxESrhbjXVlNpEgWegN364I8naURqyya0JE3boT1l/+fnV9vqxpk+q6qsZZMG0GU4n3n6NMI",
	"HS/H7IAaBj3fkFQKTj9lPWpzpRG6e25csijQWp4hNLhw0HtFLE6iZjqH48M+9F69k/oBrYugd0KvERy/",
	"UzRSyQhO3uUiy7ubc2sOsjSmPSWLWimhhA0HFhEaQ0KqkzCx3nMp0oBiD58yQ0iOnZ3o9HrY7kYNw33C",
	"c0tDok/wDWf7E3y1Hl9B7ppLV4DV/X1z0+Ph4d4LY3WtrRUTiWS1Ci1wg/FY9eD8/cVVDBdapdSb6Pft",
	"VQy3unJ5/fOu/gl3aF0NGzSwAW9gl8MYLkUquUptgAxOY/8dTlUmBQ/A0VUMI20a6qNB/bNFaXTXwFoc",
	"z2K4TbQj8gFydxrDHZdYMxsN60NoFAwNBsSV2/zFFYsY6Rced+Ex8I/LoX8MTv1jFFBG4duoxjzzj7sa",
	"ZbjvcqB20I/vBm6WA+uPTH7ziK316Y2ilOTcDdMtQU0fYfgBtIHM6KpsAE+m/qvtKXiOLuTHX99r95GT",
	"B+n2/mnZ+/ef4ZpsqRXoype9divP2qpQLVrfhSz3KGcruPUOBS2Etdb6cPhJAzFxwDsRqCgLZ5uqHFGF",
	"8Wk8ZmMGB1iUbgbBTodBLv9eJz0hfvnaoPloCFgkbQund+KhqirQiGTx4UfWM3uuY67WzVPvj/qwMIzT",
	"i550wFtLm0NvDOid/IwtTath+fXLU0uXXf3h5+5vtlpob61bGfk/27+8wI+ex485ceu6pr2pWNvD7Le/",
	"X71gzL9Gz9rfPNca3Vue2jZcQSt/4cvXYKr9B9mCmkdJgTjl0i5g/0KjN8bd33bsdkb77XReEA7Bw2vx",
	"sL2/vFld6Ozn1aahbvpz3xXQi3xbU/wj/LlxfQnVbbNPEp5QU+2XOMJJ/6fOg3BJTk5e7WmXOkVpWcTu",
	"0dhgv5P+cf+Yuq0uUfFSsJi97h/331AL4S4nH83n/w0AAP//t92vWtccAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
