# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: 3.0.4

info:
  title: Twitchets Configuration API
  description: API for managing Twitchets configuration
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /config:
    get:
      summary: Get current configuration
      description: Retrieve the current Twitchets configuration
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Config"
        "500":
          description: Internal server error

    put:
      summary: Update configuration
      description: Update the Twitchets configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Config"
      responses:
        "200":
          description: Configuration updated successfully
        "400":
          description: Invalid configuration
        "500":
          description: Internal server error

components:
  schemas:
    Config:
      type: object
      properties:
        apiKey:
          type: string
          description: "REQUIRED: See README.md for details on how to obtain"
        country:
          type: string
          description: Currently only GB is supported
        notification:
          $ref: "#/components/schemas/NotificationConfig"
        global:
          $ref: "#/components/schemas/GlobalTicketListingConfig"
        tickets:
          type: array
          items:
            $ref: "#/components/schemas/TicketListingConfig"

    NotificationConfig:
      type: object
      description: |
        Notification service configuration
      properties:
        ntfy:
          $ref: "#/components/schemas/NtfyConfig"
        gotify:
          $ref: "#/components/schemas/GotifyConfig"
        telegram:
          $ref: "#/components/schemas/TelegramConfig"

    NtfyConfig:
      type: object
      properties:
        url:
          description: You can use the public instance at https://ntfy.sh
          type: string
        topic:
          description: "If using https://ntfy.sh, make sure this is unique to you!"
          type: string
        username:
          description: "Optional: for authenticated instances"
          type: string
        password:
          description: "Optional: for authenticated instances"
          type: string

    GotifyConfig:
      type: object
      properties:
        url:
          description: Your Gotify server URL
          type: string
        token:
          description: Application token from Gotify
          type: string

    TelegramConfig:
      type: object
      properties:
        token:
          description: Get from @BotFather on Telegram
          type: string
        chatId:
          description: Your chat ID or group chat ID
          type: integer

    GlobalTicketListingConfig:
      type: object
      description: |
        Global ticket configuration
        All available settings are outlined below
        These settings apply to all tickets by default
        Individual ticket configuration can override these settings
        Settings can be added and removed as needed
        Any setting not specified will use the default
      properties:
        eventSimilarity:
          description: |
            Event name similarity matching (0.0 - 1.0).
            Default: 0.9 (allows for minor naming differences)
          type: number
          format: double
        regions:
          description: |
            Geographic regions to search for tickets.
            Default: All regions if not specified.
            Full list: https://github.com/ahobsonsayers/twigots/blob/main/location.go#L79-L90
          type: array
          items:
            $ref: "#/components/schemas/Region"
        numTickets:
          description: |
            Minimum number of tickets required in listing
            Default: Any number of tickets.
          type: integer
        discount:
          description: |
            Minimum discount (including fee) on the original price as a percentage
            Default: Any discount (including no discount).
          type: number
          format: double
        maxTicketPrice:
          description: |
            Maximum price per ticket (including fee) in pounds (£)
            Default: Any price.
          type: number
          format: double
        notification:
          description: |
            Notification services to use
            Default: All configured services.
          type: array
          items:
            $ref: "#/components/schemas/NotificationService"

    TicketListingConfig:
      type: object
      description: |
        Individual ticket configuration
        Available settings match the global ones
        Settings here override global settings above
        To reset a global setting to its default, use:
        - "" (empty string) for string values
        - [] (empty array) for list values
        - -1 for numeric values
      properties:
        event:
          description: Event name
          type: string
        eventSimilarity:
          description: |
            Event name similarity matching (0.0 - 1.0).
            Overrides global setting.
          type: number
          format: double
        regions:
          description: |
            Geographic regions to search for tickets
            Overrides global setting. To reset to default (all regions), use an empty array [].
          type: array
          items:
            $ref: "#/components/schemas/Region"
        numTickets:
          description: |
            Number of tickets required in listing
            Overrides global setting. To reset to default (any number), use -1.
          type: integer
        discount:
          description: |
            Minimum discount on the original price as a percentage
            Overrides global setting. To reset to default (any discount), use -1.
          type: number
          format: double
        maxTicketPrice:
          description: |
            Maximum price per ticket (including fee) in pounds (£)
            Overrides global setting. To reset to default (any price), use -1.
          type: number
          format: double
        notification:
          description: |
            Notification services to use
            Overrides global setting. To reset to default (all configured services), use an empty array [].
          type: array
          items:
            $ref: "#/components/schemas/NotificationService"

    Region:
      type: string
      description: |
        A geographic region code. 
        Possible values are:
        - GBLO: London
        - GBSO: South
        - GBSW: South West
        - GBSE: South East
        - GBMI: Midlands
        - GBEA: East Anglia
        - GBNO: North
        - GBNE: North East
        - GBNW: North West
        - GBSC: Scotland
        - GBWA: Wales
        - GBNI: Northern Ireland

        Full list: https://github.com/ahobsonsayers/twigots/blob/main/location.go#L79-L90
      enum:
        - GBLO
        - GBSO
        - GBSW
        - GBSE
        - GBMI
        - GBEA
        - GBNO
        - GBNE
        - GBNW
        - GBSC
        - GBWA
        - GBNI

    NotificationType:
      type: string
      enum:
        - ntfy
        - gotify
        - telegram
